### ISSUE TITLE
illuminatio should support NetworkPolicies with empty ports

### ISSUE THREAD

**Issue by sjentzsch** [inovex/illuminatio#102]
When running `illuminatio` version 1.3.2 via Python 3.6.9 on my cluster with `illuminatio clean run`, I get the following error:

```
$ illuminatio clean run
Starting cleaning resources with policies ['on-request', 'always']
Finished cleanUp
Starting test generation and run.
Traceback (most recent call last):
  File "/home/sjentzsch/.local/bin/illuminatio", line 8, in <module>
    sys.exit(cli())
  File "/home/sjentzsch/.local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/sjentzsch/.local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/sjentzsch/.local/lib/python3.6/site-packages/click/core.py", line 1289, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/home/sjentzsch/.local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sjentzsch/.local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/sjentzsch/.local/lib/python3.6/site-packages/illuminatio/illuminatio.py", line 111, in run
    net_pols.items, orch.current_namespaces
  File "/home/sjentzsch/.local/lib/python3.6/site-packages/illuminatio/test_generator.py", line 99, in generate_test_cases
    case = NetworkTestCase(other_host, rule_host, on_port, True)
  File "/home/sjentzsch/.local/lib/python3.6/site-packages/illuminatio/test_case.py", line 20, in __init__
    raise ValueError("onPort may not be None")
ValueError: onPort may not be None
```
Within the cluster I have several services with `clusterIP: None` - could it be related?

Thanks for any hint/idea on how to fix it ! :-)

**Comment by sjentzsch** [comment]
Nevermind, caused by a `NetworkPolicy` with empty port block:

```
  ingress:
  - ports:
    - port: 80
      protocol: TCP
    - port: 443
      protocol: TCP
    - protocol: TCP
```

**Comment by johscheuer** [comment]
Hi, thanks for using illuminatio and reporting this bug. I reopen this issue since this is a total valid use-case and illuminatio should be able to work with this. From the docs:

```bash
The port on the given protocol. This can either be a numerical or named
port on a pod. If this field is not provided, this matches all port names
and numbers.
```
