### ISSUE TITLE
NetworkPolicies are translated into ExternalHosts when pod selector contains dots

### ISSUE THREAD

**Issue by axelgobletbdr** [inovex/illuminatio#104]
One of our network policies contains a pod selector with dots in it: `app.kubernetes.io/component=metadata`. This causes illuminatio to classify this as `ExternalHost` [here](https://github.com/inovex/illuminatio/blob/master/src/illuminatio/host.py#L35). When executing `illuminatio run`, this causes a `ValueError`:

```
Traceback (most recent call last):
  File "/home/axel/miniconda3/envs/ansible/bin/illuminatio", line 11, in <module>
    load_entry_point('illuminatio', 'console_scripts', 'illuminatio')()
  File "/home/axel/miniconda3/envs/ansible/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/axel/miniconda3/envs/ansible/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/axel/miniconda3/envs/ansible/lib/python3.8/site-packages/click/core.py", line 1289, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/home/axel/miniconda3/envs/ansible/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/axel/miniconda3/envs/ansible/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/axel/repos/github/inovex/illuminatio/src/illuminatio/illuminatio.py", line 144, in run
    ) = execute_tests(cases, orch, cri_socket)
  File "/home/axel/repos/github/inovex/illuminatio/src/illuminatio/illuminatio.py", line 199, in execute_tests
    ) = orch.ensure_cases_are_generated(core_api)
  File "/home/axel/repos/github/inovex/illuminatio/src/illuminatio/test_orchestrator.py", line 430, in ensure_cases_are_generated
    ) = self._find_or_create_cluster_resources_for_cases(cases_dict, core_api)
  File "/home/axel/repos/github/inovex/illuminatio/src/illuminatio/test_orchestrator.py", line 366, in _find_or_create_cluster_resources_for_cases
    ) = self._get_target_names_creating_them_if_missing(target_dict, api)
  File "/home/axel/repos/github/inovex/illuminatio/src/illuminatio/test_orchestrator.py", line 228, in _get_target_names_creating_them_if_missing
    raise ValueError(
ValueError: Only ClusterHost targets are supported by this Orchestrator. Host: ExternalHost(ipAddress=kubeflow:app.kubernetes.io/component=metadata), hostString: kubeflow:app.kubernetes.io/component=metadata
```

I think that the behavior should be that this pod selector is treated as any other pod selector without periods in it.

**Comment by maxbischoff** [comment]
Thanks for opening this issuse, I'm looking into it.
