### ISSUE TITLE
Illuminatio tries to create service with invalid name

### ISSUE THREAD

**Issue by axelgobletbdr** [inovex/illuminatio#105]
From a network policy with pod selector `app.kubernetes.io/component=kubernetes-dashboard`, Illuminatio tries to create the following service:

```
{'api_version': 'v1',
 'kind': 'Service',
 'metadata': {'annotations': None,
              'cluster_name': None,
              'creation_timestamp': None,
              'deletion_grace_period_seconds': None,
              'deletion_timestamp': None,
              'finalizers': None,
              'generate_name': None,
              'generation': None,
              'initializers': None,
              'labels': {'illuminatio-cleanup': 'always',
                         'illuminatio-role': 'test_target_svc'},
              'managed_fields': None,
              'name': 'svc-kubernetes-dashboard-app.kubernetes.io/componentkubernetes-dashboard',
              'namespace': 'kubernetes-dashboard',
              'owner_references': None,
              'resource_version': None,
              'self_link': None,
              'uid': None},
 'spec': {'cluster_ip': None,
          'external_i_ps': None,
          'external_name': None,
          'external_traffic_policy': None,
          'health_check_node_port': None,
          'load_balancer_ip': None,
          'load_balancer_source_ranges': None,
          'ports': [{'name': None,
                     'node_port': None,
                     'port': 36440,
                     'protocol': 'TCP',
                     'target_port': 80}],
          'publish_not_ready_addresses': None,
          'selector': {'app.kubernetes.io/component': 'kubernetes-dashboard',
                       'illuminatio-role': 'test_target_pod'},
          'session_affinity': None,
          'session_affinity_config': None,
          'type': None},
 'status': None}
```

This creation fails with the following error:
```
Traceback (most recent call last):
  File "/home/axel/miniconda3/envs/ansible/bin/illuminatio", line 11, in <module>
    load_entry_point('illuminatio', 'console_scripts', 'illuminatio')()
  File "/home/axel/miniconda3/envs/ansible/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/axel/miniconda3/envs/ansible/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/axel/miniconda3/envs/ansible/lib/python3.8/site-packages/click/core.py", line 1289, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/home/axel/miniconda3/envs/ansible/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/axel/miniconda3/envs/ansible/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/axel/repos/github/inovex/illuminatio/src/illuminatio/illuminatio.py", line 144, in run
    ) = execute_tests(cases, orch, cri_socket)
  File "/home/axel/repos/github/inovex/illuminatio/src/illuminatio/illuminatio.py", line 199, in execute_tests
    ) = orch.ensure_cases_are_generated(core_api)
  File "/home/axel/repos/github/inovex/illuminatio/src/illuminatio/test_orchestrator.py", line 431, in ensure_cases_are_generated
    ) = self._find_or_create_cluster_resources_for_cases(cases_dict, core_api)
  File "/home/axel/repos/github/inovex/illuminatio/src/illuminatio/test_orchestrator.py", line 367, in _find_or_create_cluster_resources_for_cases
    ) = self._get_target_names_creating_them_if_missing(target_dict, api)
  File "/home/axel/repos/github/inovex/illuminatio/src/illuminatio/test_orchestrator.py", line 291, in _get_target_names_creating_them_if_missing
    resp = api.create_namespaced_service(namespace=host.namespace, body=svc)
  File "/home/axel/miniconda3/envs/ansible/lib/python3.8/site-packages/kubernetes/client/apis/core_v1_api.py", line 6934, in create_namespaced_service
    (data) = self.create_namespaced_service_with_http_info(namespace, body, **kwargs)
  File "/home/axel/miniconda3/envs/ansible/lib/python3.8/site-packages/kubernetes/client/apis/core_v1_api.py", line 7012, in create_namespaced_service_with_http_info
    return self.api_client.call_api('/api/v1/namespaces/{namespace}/services', 'POST',
  File "/home/axel/miniconda3/envs/ansible/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 330, in call_api
    return self.__call_api(resource_path, method,
  File "/home/axel/miniconda3/envs/ansible/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 163, in __call_api
    response_data = self.request(method, url,
  File "/home/axel/miniconda3/envs/ansible/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 371, in request
    return self.rest_client.POST(url,
  File "/home/axel/miniconda3/envs/ansible/lib/python3.8/site-packages/kubernetes/client/rest.py", line 260, in POST
    return self.request("POST", url,
  File "/home/axel/miniconda3/envs/ansible/lib/python3.8/site-packages/kubernetes/client/rest.py", line 222, in request
    raise ApiException(http_resp=r)
kubernetes.client.rest.ApiException: (422)
Reason: Unprocessable Entity
HTTP response headers: HTTPHeaderDict({'Audit-Id': '2fa73239-1a5c-4b1b-9d79-e46ac1c4b493', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Date': 'Tue, 14 Jul 2020 14:54:54 GMT', 'Content-Length': '1423'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Service \"svc-kubernetes-dashboard-app.kubernetes.io/componentkubernetes-dashboard\" is invalid: [metadata.name: Invalid value: \"svc-kubernetes-dashboard-app.kubernetes.io/componentkubernetes-dashboard\": must be no more than 63 characters, metadata.name: Invalid value: \"svc-kubernetes-dashboard-app.kubernetes.io/componentkubernetes-dashboard\": a DNS-1035 label must consist of lower case alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character (e.g. 'my-name',  or 'abc-123', regex used for validation is '[a-z]([-a-z0-9]*[a-z0-9])?')]","reason":"Invalid","details":{"name":"svc-kubernetes-dashboard-app.kubernetes.io/componentkubernetes-dashboard","kind":"Service","causes":[{"reason":"FieldValueInvalid","message":"Invalid value: \"svc-kubernetes-dashboard-app.kubernetes.io/componentkubernetes-dashboard\": must be no more than 63 characters","field":"metadata.name"},{"reason":"FieldValueInvalid","message":"Invalid value: \"svc-kubernetes-dashboard-app.kubernetes.io/componentkubernetes-dashboard\": a DNS-1035 label must consist of lower case alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character (e.g. 'my-name',  or 'abc-123', regex used for validation is '[a-z]([-a-z0-9]*[a-z0-9])?')","field":"metadata.name"}]},"code":422}
```

The message states that the name is too long and contains invalid characters.

**Comment by johscheuer** [comment]
Thanks for reporting this issue, we will take a look (or feel free to create a PR :)).

**Comment by johscheuer** [comment]
@maxbischoff this should be resolved with the `generate_name` change?
